#!/bin/sh
# Script de consulta a facebook por numero de telefono movil
# (c) www.hackingyseguridad.com 2017
echo
echo
echo "Uso: ./facebook <Numero_telefono>"
echo
curl https://www.facebook.com/search/top/?q=$1 |grep EntRegularPersonalUser
